name: consent_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  video_player: ^2.5.0
  visibility_detector: ^0.3.3
  subtitle: ^0.1.0-beta.3
  get_it: ^7.2.0
  i18n_extension: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images & video directory to the application.
    - assets/images/
    - assets/video/

fonts:
  - family: Frutiger
    fonts:
      - asset: assets/fonts/Frutiger.ttf
        weight: 400
      - asset: assets/fonts/Frutiger_bold.ttf
        weight: 700